name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.7.1
  firebase_auth_auto_route:
    path: ../../firebase_auth_auto_route

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.2.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
